config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Big John's online store</title>
  <%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= @page_title || "John's Store" %>
  </div>
  <div id="columns">
    <div id="side">
    <% if @cart %>
      <div id="cart">
        <%= render @cart %>
      </div>
    <% end %>

      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/admin">Admin</a></li>
      </ul>

      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders',   orders_path   %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete   %>
      <% end %>

    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>